spring:
  application:
    name: spring-rest-api

  h2:
    console:
      enabled: true
      path: /h2-console

  sql:
    init:
      mode: always

  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: none
      use-new-id-generator-mappings: false
    show-sql: false

  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:testdb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    username: sa
    password:

logging.level:
  org.hibernate.SQL: info

decorator:
  datasource:
    p6spy:
      enable-logging: true
      logging: slf4j
      multiline: true

jwt:
  secret: dummy-secret-a9d8fasf8oscjv8p-asf89asdixcuDOSISDiojdsio9afo
  access-token-exp-seconds: 180
  refresh-token-exp-seconds: 12096000